"use client";
import { motion } from "framer-motion";import { useEffect,useRef } from "react";import { useRouter } from "next/navigation";import { Guard } from "@/components/Guard";import { Button,Card,Page } from "@/components/UI";import { useAppState } from "@/components/StateProvider";import { riskBand } from "@/lib/state";import { track } from "@/lib/track";
const sections=[
 {id:"meaning",title:"지금 결과가 의미하는 것",body:<><p>STOP-BANG은 수면무호흡 위험을 확인하는 선별검사이며 확진 검사가 아닙니다. 점수가 높을수록 추가 평가가 필요할 가능성을 뜻합니다. 확진은 의료진의 평가와 수면다원검사(polysomnography)를 통해 이루어집니다.</p></>},
 {id:"importance",title:"왜 방치하면 안 되나요",body:<><p>치료하지 않은 폐쇄성 수면무호흡은 심혈관 건강, 대사 건강, 주간 졸림 등과 관련될 수 있습니다. 증상과 영향은 사람마다 다르므로 의료진과 상담해 개인 상태를 확인하는 것이 중요합니다. 구체적인 위험은 개인의 건강 상태에 따라 달라집니다. [출처 확인 필요]</p></>},
 {id:"diagnosis",title:"어떻게 진단하나요",body:<ol className="steps"><li className="step"><span className="step-num">1</span><div><b>진료 상담</b><p>증상과 건강 상태를 의료진과 상담합니다.</p></div></li><li className="step"><span className="step-num">2</span><div><b>수면다원검사</b><p>수면 중 호흡·산소포화도·수면단계를 측정합니다.</p></div></li><li className="step"><span className="step-num">3</span><div><b>결과 상담</b><p>검사 결과와 다음 단계를 상담합니다.</p></div></li><li><p className="caption">[보험·비용 안내 문구]</p></li></ol>},
 {id:"treatment",title:"어떤 치료가 있나요",body:<ul className="list"><li><b>양압기(CPAP)</b>: 수면 중 기도에 일정한 압력의 공기를 공급하는 치료입니다.</li><li><b>구강내장치</b>: 아래턱이나 혀의 위치를 조절해 기도를 확보하는 장치입니다.</li><li><b>수술</b>: 해부학적 원인을 고려해 의료진이 검토할 수 있는 방법입니다.</li><li><b>생활습관 교정</b>: 체중 관리, 수면 자세, 음주 습관 등을 조절하는 방법입니다.</li></ul>}
];
export default function Learn(){const {state}=useAppState();const router=useRouter();const sent=useRef(new Set<number>());useEffect(()=>{const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(max<=0)return;const pct=Math.round(scrollY/max*100);[25,50,75,100].forEach(n=>{if(pct>=n&&!sent.current.has(n)){sent.current.add(n);track("learn_scroll_depth",{percent:n},2)}})};addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);return <Guard><Page className="stack24"><Card className="stack16"><span className="badge">{riskBand(state.score??5)}</span><h1>8점 중 {state.score??5}점</h1><div className="gauge"><motion.div initial={{width:0}} animate={{width:`${((state.score??5)/8)*100}%`}} transition={{duration:.6,ease:[.22,1,.36,1]}}/></div></Card>{sections.map((s,i)=><motion.section key={s.id} viewport={{once:true,amount:.3}} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} transition={{duration:.22,delay:i*.04,ease:[.22,1,.36,1]}} onViewportEnter={()=>track("learn_section_view",{sectionId:s.id},2)}><Card className="stack16"><h2>{s.title}</h2>{s.body}</Card></motion.section>)}<div className="sticky-cta"><Button aria-label="검사 예약 알아보기" onClick={()=>{track("cta_click",{id:"learn_booking",label:"검사 예약 알아보기"},2);router.push("/choose")}}>검사 예약 알아보기</Button></div></Page></Guard>}
