"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Card, Button, Page } from "@/components/UI";
import { useAppState } from "@/components/StateProvider";
import { questions } from "@/data/questions";
import { riskBand } from "@/lib/state";
import { track } from "@/lib/track";
export default function Home(){const {state,setState,ready}=useAppState();const router=useRouter();const [selected,setSelected]=useState<number|null>(null);const shown=useRef(Date.now());useEffect(()=>{if(ready&&!state.started)track("intro_view")},[ready,state.started]);if(!ready)return null;const index=state.answers.length;const start=()=>{setState({started:true,answers:[],score:null});track("cta_click",{id:"intro_start",label:"체크 시작하기"},1);track("quiz_start",{},1);shown.current=Date.now()};const answer=(value:number)=>{if(selected!==null)return;setSelected(value);track("quiz_answer",{qid:questions[index].id,value,elapsedMs:Date.now()-shown.current},1);setTimeout(()=>{const answers=[...state.answers,value];if(answers.length===8){const score=answers.reduce((a,b)=>a+b,0);setState(s=>({...s,answers,score}));track("quiz_complete",{score,riskBand:riskBand(score)},1);router.push(score<=2?"/low-risk":"/learn")}else{setState(s=>({...s,answers}));setSelected(null);shown.current=Date.now()}},250)};if(!state.started||index>=8)return <Page className="stack24"><Card className="stack16"><h1>1분 수면 무호흡 위험도 체크</h1><p>간단한 8개 질문으로 수면무호흡 위험도를 확인해 보세요.<br/>결과는 의료적 진단을 대신하지 않습니다.</p><Button aria-label="체크 시작하기" onClick={start}>체크 시작하기</Button></Card></Page>;const q=questions[index];return <Page key={q.id} className="stack24"><p className="caption">{index+1} / 8</p><Card className="stack24"><h1>{q.text}</h1>{"caption" in q&&<p className="caption">{q.caption}</p>}<div className="choices"><button aria-label="예" className={`choice ${selected===1?"selected":""}`} onClick={()=>answer(1)}>예</button><button aria-label="아니오" className={`choice ${selected===0?"selected":""}`} onClick={()=>answer(0)}>아니오</button></div></Card></Page>}
